#  Minos Stavrakakis - csd4120
#  HY240 - PhaseA

clean:
	rm -rf phaseA_exec

# list: symtable.h symtablelist.o
# 	gcc -Wall -ansi -pedantic -o testsymtab testsymtab.c symtablelist.o

# symtablelist.o: symtable.h symtablelist.c
# 		gcc -c symtablelist.c

# hash: symtable.h symtablehash.o
# 	  gcc -Wall -ansi -pedantic -o testsymtab testsymtab.c symtablehash.o

# symtablehash.o: symtable.h symtablehash.c
# 		gcc -c symtablehash.c

all: 
	gcc main.c -Wall -ansi -pedantic -o phaseA_exec